create table player(
idx int primary key auto_increment,
name varchar(20) unique,
pass varchar(20),
charStatus int default 1,
turn int default 1,
speed int default 0,
power int default 0,
fatigue int default 0,
lifeCount int default 10,
food int default 5,
log int default 0,
firewood int default 10,
event varchar(20) default "",

honeyPollution int default 0,
fishPollution int default 0,

specie1 int default 0,
status1 int default 0,
passedTurn1 int default 1,
harvestTurn1 int default 40,
tempResult1 int default 0,
waterResult1 int default 0,
optimalTemp1 int default 10,
fertilized1 int default 0,
waterContent1 int default 50,
waterReduction1 int default 4,
dieTemp1 int default 4,
dieWater1 int default 4,


specie2 int default 0,
status2 int default 0,
passedTurn2 int default 1,
harvestTurn2 int default 40,
tempResult2 int default 0,
waterResult2 int default 0,
optimalTemp2 int default 10,
fertilized2 int default 0,
waterContent2 int default 50,
waterReduction2 int default 4,
dieTemp2 int default 4,
dieWater2 int default 4,

specie3 int default 0,
status3 int default 0,
passedTurn3 int default 1,
harvestTurn3 int default 40,
tempResult3 int default 0,
waterResult3 int default 0,
optimalTemp3 int default 10,
fertilized3 int default 0,
waterContent3 int default 50,
waterReduction3 int default 4,
dieTemp3 int default 4,
dieWater3 int default 4

);